### ISSUE TITLE
.env do sandbox

### ISSUE THREAD

**Issue by leandrorcamargo** [allisson/django-pagseguro2-example#1]
Olá Allison,
No .end do sandbox que devo editar tem uma tal de secret-key. 
Não acho ela nos meus dados do pagseguro, apenas acho o token e os outros dados. Esta informação é do pagseguro mesmo? Se sim, sabe em qual tela a encontro? Já procurei em todos lugares.

Valeu!

**Comment by allisson** [comment]
O secret-key é usando na configuração settings.SECRET_KEY do django, não tem relação com o pagseguro :+1:
